- name: Create consul directories structure
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ consul_user }}"
    group: "{{ consul_user }}"
    mode: 0775
  loop:
    - "{{ consul_binary_linpath }}"
    - "{{ consul_config_linpath }}"
    - "{{ consul_log_linpath }}"

- name: Create consul data directory
  become: yes
  file:
    path: "{{ consul_data_linpath }}"
    state: directory
    recurse: yes
    owner: "{{ consul_user }}"
    group: "{{ consul_user }}"
    mode: 0775

- name: Download Consul zip file
  become: yes
  get_url:
    url: "{{ consul_url }}"
    dest: "{{ consul_binary_linpath }}"
    mode: 0750

- name: Uncompress source compressed file
  become: yes
  unarchive:
    src: "{{ consul_zip_linpath }}"
    dest: "{{ consul_binary_linpath }}"
    remote_src: yes

- name: Remove compressed file
  become: yes
  file:
    path: "{{ consul_zip_linpath }}"
    state: absent

- name: Register $PATH as var
  shell: echo $PATH
  register: path

- set_fact:
    path_list: "{{ path.stdout.split(':') }}"

- name: Add {{ consul_binary_linpath }} to .bashrc
  lineinfile:
    dest: "{{ shell_files.bashrc.linpath }}"
    line: 'export PATH={{ consul_binary_linpath }}:$PATH'
    insertafter: EOF
  when: consul_binary_linpath not in path_list

- name: Transfer certificates to every Consul server
  copy:
    src: ../{{ item }}
    dest: "{{ consul_config_linpath }}/"
    mode: 0755
  loop:
   - consul-agent-ca.pem
   - dc1-server-consul-0.pem
   - dc1-server-consul-0-key.pem

- name: Copy base.hcl
  template:
    src: base.hcl
    dest: "{{ consul_config_linpath }}/base.hcl"
    mode: 0755

- name: Copy server.hcl into consul Client
  template:
    src: server.hcl
    dest: "{{ consul_config_linpath }}/server.hcl"
    mode: 0755
  when: consul_server

- name: Copy consul.service
  become: yes
  template:
    src: consul.service
    dest: "/etc/systemd/system/consul.service"
    mode: 0755

- name: Start Consul service
  become: yes
  systemd:
    enabled: yes
    state: started
    daemon_reload: yes
    name: consul