- name: Copy consul.hcl into Consul server
  become: yes
  template:
    src: consul.hcl
    dest: "/etc/consul.d/consul.hcl"
    mode: 0755

- name: Copy consul.service into Consul server
  become: yes
  template:
    src: consul.service
    dest: "/usr/lib/systemd/system/consul.service"
    mode: 0755

- name: Enable service consul and ensure it is not masked
  become: yes
  systemd:
    name: consul
    enabled: yes
    masked: no

- name: Restart consul service
  become: yes
  systemd:
    state: restarted
    daemon_reload: yes
    name: consul