- name: Change dirs permissions
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ consul_user }}"
    group: "{{ consul_user }}"
    mode: 0775
  loop:
    - "{{ consul_binary_linpath }}"
    - "{{ consul_config_linpath }}"
    - "{{ consul_log_linpath }}"

- name: Copy base.hcl
  template:
    src: base.hcl
    dest: "{{ consul_config_linpath }}/base.hcl"
    owner: "{{ consul_user }}"
    group: "{{ consul_user }}"
    mode: 0755

- name: Copy server.hcl into consul Client
  template:
    src: server.hcl
    dest: "{{ consul_config_linpath }}/server.hcl"
    owner: "{{ consul_user }}"
    group: "{{ consul_user }}"
    mode: 0755
  when: consul_server

- name: Copy consul.service
  become: yes
  template:
    src: consul.service
    dest: "/etc/systemd/system/consul.service"
    mode: 0755

- name: Start Consul service
  become: yes
  systemd:
    enabled: yes
    state: started
    daemon_reload: yes
    name: consul