- name: Copy remove_service.sh script
  copy:
    src: remove_service.sh
    dest: "{{ ansible_user_dir }}/"
    mode: 0777

- name: Execute remove_service.sh script
  command: "{{ ansible_user_dir }}/remove_service.sh"

- name: Delete all consul files
  become: yes
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ consul_path }}"
    - "{{ consul_data_linpath }}"
    - "{{ ansible_user_dir }}/remove_service.sh"