- name: Deploy consul
  gather_facts: yes
  hosts: "{{ host_group }}"
  vars_files:
    - group_vars/linux.yml
  tasks:
    - name: Start consul role
      include_role: 
        name: consul
      tags: always  