- name: Deploy nomad
  gather_facts: yes
  hosts: "{{ host_group }}"
  vars_files:
    - group_vars/linux.yml
  tasks:
    - name: Bootstrap the server
      yum:
        name: unzip
        state: present
      tags: always  

    - name: Start nomad role
      include_role: 
        name: nomad
      tags: always  