- name: Deploy Nomad Client installation on Windows
  gather_facts: yes
  hosts: "{{ host_group }}"
  vars_files:
    - group_vars/windows.yml
  tasks:
    - name: Start nomad_client_windows role
      include_role:
        name: nomad_client_windows
      tags: always