- name: Deploy nomad
  gather_facts: yes
  hosts: "{{ host_group }}"
  vars_files:
    - group_vars/linux.yml
  tasks:
    - include: roles/nomad/tasks/setup.yml
      tags: setup
    - include: roles/nomad/tasks/enable_start.yml
      tags: enable_start    