- name: Deploy nomad
  gather_facts: yes
  hosts: "{{ host_group }}"
  vars_files:
    - group_vars/linux.yml
  tasks:
    - include_tasks: roles/nomad/tasks/main.yml
      apply:
        tags:
          - setup
          - enable_start