- name: Copy remove_service.sh script
  copy:
    src: remove_service.sh
    dest: "{{ nomad_path }}"
    mode: 0777

- name: Execute remove_service.sh script
  command: "{{ nomad_path }}/remove_service.sh"

- name: Delete all Nomad files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ nomad_path }}"
    - "{{ nomad_data_linpath }}"